class cfgPatches
{
	class XI_Sector_Pirates
	{
		units[]=
		{
			"XI_Light_Lasgun_1_Pirate",
			"XI_Light_Lasgun_2_Pirate",
			"XI_Light_Autogun_1_Pirate",
			"XI_Light_Autogun_2_Pirate",
			"XI_Light_AT_1_Pirate",
			"XI_Light_Melta_1_Pirate",
			"XI_Light_Melta_1_Irregular",
			"XI_Light_AT_1_Irregular",
			"XI_Light_Lasgun_1_Irregular",
			"XI_Light_Lasgun_2_Irregular",
			"XI_Light_Autogun_1_Irregular",
			"XI_Light_Autogun_2_Irregular",
			"XI_Light_Lasgun_1_Skirmisher",
			"XI_Light_Lasgun_2_Skirmisher",
			"XI_Light_Autogun_1_Skirmisher",
			"XI_Light_Autogun_2_Skirmisher",
			"XI_Light_AT_1_Skirmisher",
			"XI_Light_Melta_1_Skirmisher",
			"XI_Line_Lasgun_1_Pirate",
			"XI_Line_Lasgun_2_Pirate",
			"XI_Line_Autogun_1_Pirate",
			"XI_Line_Autogun_2_Pirate",
			"XI_Line_AT_1_Pirate",
			"XI_Line_Melta_1_Pirate",
			"XI_Line_Marksman_1_Pirate",
			"XI_Shock_Lasgun_1_Pirate",
			"XI_Shock_Bolter_1_Pirate",
			"XI_Shock_Xeno_1_Pirate",
			"XI_Light_Crewman_1_Pirate",
			"XI_Light_Crewman_1_Pirate_1",
			"XI_Light_Crewman_1_Pirate_2",
			"XI_Light_Crewman_1_Pirate_3",
			"XI_Pirate_AAA",
			"XI_Pirate_Multilas",
			"XI_Pirate_Autogun",
			"XI_Pirate_HE",
			"XI_Pirate_AT",
			"XI_Pirate_APC",
			"XI_Pirate_APC_2",
			"XI_Pirate_APC_3",
			"XI_Pirate_Supply_Vehicle",
			"XI_Pirate_Transport_car",
			"XI_Pirate_Technical",
			"XI_Pirate_Dropship_1",
			"XI_Pirate_Interceptor_1",
			"XI_Pirate_Dropship_Helicopter_1",
			"XI_Pirate_Dropship_2",
			"XI_Pirate_Interceptor_2",
			"XI_Pirate_Dropship_Helicopter_2",
			"XI_Pirate_Adavnced_APC",
			"XI_Pirate_Light_transport",
			"XI_Pirate_Light_Tank_1",
			"XI_Pirate_Hijacked_Tank_1",
			"XI_Pirate_Heavy_Tank_Plasma",
			"XI_Pirate_Heavy_Tank_Battle",
			"XI_Pirate_Hijacked_APC",
			"XI_Pirate_APC_1",
			"XI_Pirate_Destroyer_1",
			"XI_Pirate_ARV_1",
			"XI_Pirate_Valkyrie_1",
			"XI_Pirate_Light_Helicopter_1"
		};
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"XI_ic_cad_autogun",
			"XI_IC_CAD_Rocketlauncher_base",
			"XI_ic_cad_melta",
			"XI_ic_cad_LuciusLongLas_optic_LRPS",
			"XI_IC_Hellgun_ic_hellgun_optic",
			"XI_ic_cad_bolter",
			"XI_ic_PulseRifleW"
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"ace_medical_treatment",
			"A3_Weapons_F",
			"ace_parachute",
			"IC_Weapons_Kantrael",
			"xi",
			"xi_cf",
			"TIOW_Valhallans",
			"A3_Characters_F",
			"CuratorOnly_Characters_F_BLUFOR",
			"Renegades_Foot",
			"IC_Weapons_Autogun01",
			"DkoKFoot",
			"IC_Weapons_Launchers",
			"IC_Departmento_Weapons",
			"IC_Chaos",
			"winchester",
			"A3_Characters_F_Exp",
			"A3_Characters_F_Enoch",
			"IC_weapons_Acc",
			"IC_Guevesa",
			"A3_Characters_F_Tank_Headgear"
		};
	};
};
class cfgFactionClasses
{
	class XI_Sector_Pirates
	{
		icon="";
		displayName="Sector Pirates";
		side=0;
		priority=1;
	};
};
class cfgWeapons
{
	class ic_cad_m36_lasgun;
	class ic_cad_autogun;
	class IC_CAD_Rocketlauncher_base;
	class ic_cad_melta;
	class ic_cad_LuciusLongLas;
	class IC_Hellgun;
	class ic_cad_bolter;
	class ic_PulseRifleW;
	class XI_ic_cad_m36_lasgun: ic_cad_m36_lasgun
	{
		displayName="[Imperium] M36 Kantrael Lasgun";
		scope=1;
		class LinkedItems
		{
		};
	};
	class XI_ic_cad_autogun: ic_cad_autogun
	{
		displayName="[Imperium] Agripinaa Ptrn. Type III Autogun";
		scope=1;
		class LinkedItems
		{
		};
	};
	class XI_IC_CAD_Rocketlauncher_base: IC_CAD_Rocketlauncher_base
	{
		displayName="[Imperium] Cadian Rocket Launcher";
		scope=1;
		class LinkedItems
		{
		};
	};
	class XI_ic_cad_melta: ic_cad_melta
	{
		displayName="[Imperium] Meltagun";
		scope=1;
		class LinkedItems
		{
		};
	};
	class XI_ic_cad_LuciusLongLas_optic_LRPS: ic_cad_LuciusLongLas
	{
		displayName="[Imperium] Nemesis Tessera Pattern LongLas";
		scope=1;
		class LinkedItems
		{
		};
	};
	class XI_IC_Hellgun_ic_hellgun_optic: IC_Hellgun
	{
		displayName="[Imperium] Ryza Pattern Hellgun";
		scope=1;
		class LinkedItems
		{
		};
	};
	class XI_ic_cad_bolter: ic_cad_bolter
	{
		displayName="[Imperium] Locke pattern Bolter";
		scope=1;
		class LinkedItems
		{
		};
	};
	class XI_ic_PulseRifleW: ic_PulseRifleW
	{
		displayName="[Gue'vesa] Pulse Rifle White";
		scope=1;
		class LinkedItems
		{
		};
	};
};
class cfgVehicles
{
	class B_Soldier_A_F;
	class ic_CarryAll;
	class XI_OPfor_AA_1;
	class CadianMultilasCarriageTwin;
	class CadianAutocannonCarriageTwin;
	class XI_TOH_DeathHammer_FixedHE;
	class XI_TOH_DeathHammer_FixedAT;
	class C_mako1_alWood_F;
	class C_makoAA_alWood_F;
	class I_M080apc1_merc_F;
	class C_M080apc2_service_al_F;
	class MEOP_B_veh_LandVan_F;
	class MEOP_B_veh_LandPickupA_gang_F;
	class MEOP_veh_kodiak3_allianceWood;
	class MEOP_SX3fighter_veh_mercBlue_F;
	class MEOP_veh_ta62_facinus;
	class MEOP_veh_turKod_BS;
	class MEOP_SX4fighter_veh_cerbRed_F;
	class MEOP_veh_a61_batar;
	class C_hammer1_cerbRed_F;
	class C_mako_m32_ERCS_F;
	class O_MBT_04_command_F;
	class O_T_MBT_02_cannon_ghex_F;
	class TIOW_Krieg_LR_Executioner_1489th_OP;
	class TIOW_Krieg_LR_Battlecannon_1489th_OP;
	class O_T_APC_Wheeled_02_rcws_v2_ghex_F;
	class IC_Chimera_01_desert;
	class B_T_AFV_Wheeled_01_up_cannon_F;
	class B_T_APC_Tracked_01_CRV_F;
	class TIOW_Valkyrie_Rocket_AC_B;
	class B_Heli_Light_01_dynamicLoadout_F;
	class XI_Light_Lasgun_1_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Lasgun 1 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_Valhallan_brown_Cap",
			"xi_cadianwebbing_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_Valhallan_brown_Cap",
			"xi_cadianwebbing_light"
		};
		backpack="";
	};
	class XI_Light_Lasgun_2_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Lasgun 2 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_2";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_RenEnforcerMask_1",
			"xi_cadianArmourV2_LIGHT"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_RenEnforcerMask_1",
			"xi_cadianArmourV2_LIGHT"
		};
		backpack="";
	};
	class XI_Light_Autogun_1_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Autogun 1 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"DKoK_GM_Helm_82nd",
			"xi_cadianArmourV2_LIGHT"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"DKoK_GM_Helm_82nd",
			"xi_cadianArmourV2_LIGHT"
		};
		backpack="";
	};
	class XI_Light_Autogun_2_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Autogun 2 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_2";
		weapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"H_Cap_headphones",
			"xi_cadianArmour_LIGHT"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"H_Cap_headphones",
			"xi_cadianArmour_LIGHT"
		};
		backpack="";
	};
	class XI_Light_AT_1_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light AT 1 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"XI_IC_CAD_Rocketlauncher_base",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"XI_IC_CAD_Rocketlauncher_base",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_Valhallan_brown_Cap",
			"xi_cadianwebbing_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_Valhallan_brown_Cap",
			"xi_cadianwebbing_light"
		};
		backpack="XI_Light_AT_1_Pirate_pack";
	};
	class XI_Light_Melta_1_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Melta 1 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_melta",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_melta",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_Valhallan_brown_Cap",
			"xi_cadianwebbing_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_Valhallan_brown_Cap",
			"xi_cadianwebbing_light"
		};
		backpack="XI_Light_Melta_1_Pirate_pack";
	};
	class XI_Light_Melta_1_Irregular: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Melta 1 Irregular";
		uniformClass="IC_sos_U_rifleman_02_O";
		weapons[]=
		{
			"XI_ic_cad_melta",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_melta",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_Valhallan_brown_Cap",
			"xi_cadianwebbing_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_Valhallan_brown_Cap",
			"xi_cadianwebbing_light"
		};
		backpack="XI_Light_Melta_1_Irregular_pack";
	};
	class XI_Light_AT_1_Irregular: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light AT 1 Irregular";
		uniformClass="IC_sos_U_rifleman_01_O";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"XI_IC_CAD_Rocketlauncher_base",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"XI_IC_CAD_Rocketlauncher_base",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_Valhallan_brown_Cap",
			"xi_cadianwebbing_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_Valhallan_brown_Cap",
			"xi_cadianwebbing_light"
		};
		backpack="XI_Light_AT_1_Irregular_pack";
	};
	class XI_Light_Lasgun_1_Irregular: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Lasgun 1 Irregular";
		uniformClass="sev_uniform_irregular2";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_Valhallan_brown_Cap",
			"xi_cadianwebbing_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_Valhallan_brown_Cap",
			"xi_cadianwebbing_light"
		};
		backpack="";
	};
	class XI_Light_Lasgun_2_Irregular: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Lasgun 2 Irregular";
		uniformClass="U_BG_Guerrilla_6_1";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_RenEnforcerMask_1",
			"xi_cadianArmourV2_LIGHT"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"TIOW_RenEnforcerMask_1",
			"xi_cadianArmourV2_LIGHT"
		};
		backpack="";
	};
	class XI_Light_Autogun_1_Irregular: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Autogun 1 Irregular";
		uniformClass="U_B_GEN_Commander_F";
		weapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"DKoK_GM_Helm_82nd",
			"xi_cadianArmourV2_LIGHT"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"DKoK_GM_Helm_82nd",
			"xi_cadianArmourV2_LIGHT"
		};
		backpack="";
	};
	class XI_Light_Autogun_2_Irregular: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Autogun 2 Irregular";
		uniformClass="U_B_CombatUniform_vest_mcam_wdl_f";
		weapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"H_Cap_headphones",
			"xi_cadianArmour_LIGHT"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"H_Cap_headphones",
			"xi_cadianArmour_LIGHT"
		};
		backpack="";
	};
	class XI_Light_Lasgun_1_Skirmisher: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Lasgun 1 Skirmisher";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_darkTideHelmet_line",
			"xi_PirateVest1_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_darkTideHelmet_line",
			"xi_PirateVest1_light"
		};
		backpack="";
	};
	class XI_Light_Lasgun_2_Skirmisher: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Lasgun 2 Skirmisher";
		uniformClass="xi_CF_uniform_w_Pirate_2";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_darkTideHelmet_line",
			"xi_PirateVest1_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_darkTideHelmet_line",
			"xi_PirateVest1_light"
		};
		backpack="";
	};
	class XI_Light_Autogun_1_Skirmisher: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Autogun 1 Skirmisher";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_PirateVest1_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_PirateVest1_light"
		};
		backpack="";
	};
	class XI_Light_Autogun_2_Skirmisher: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Autogun 2 Skirmisher";
		uniformClass="xi_CF_uniform_w_Pirate_2";
		weapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_beret_light",
			"xi_PirateVest2_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_beret_light",
			"xi_PirateVest2_light"
		};
		backpack="";
	};
	class XI_Light_AT_1_Skirmisher: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light AT 1 Skirmisher";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"XI_IC_CAD_Rocketlauncher_base",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"XI_IC_CAD_Rocketlauncher_base",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_PirateVest2_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_PirateVest2_light"
		};
		backpack="XI_Light_AT_1_Skirmisher_pack";
	};
	class XI_Light_Melta_1_Skirmisher: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Melta 1 Skirmisher";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_melta",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_melta",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_PirateVest2_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_PirateVest2_light"
		};
		backpack="XI_Light_Melta_1_Skirmisher_pack";
	};
	class XI_Line_Lasgun_1_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Line Lasgun 1 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_darkTideHelmet_line",
			"xi_PirateVest1_line"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_darkTideHelmet_line",
			"xi_PirateVest1_line"
		};
		backpack="";
	};
	class XI_Line_Lasgun_2_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Line Lasgun 2 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_2";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_darkTideHelmet_line",
			"xi_PirateVest2_line"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_darkTideHelmet_line",
			"xi_PirateVest2_line"
		};
		backpack="";
	};
	class XI_Line_Autogun_1_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Line Autogun 1 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_PirateVest1_line"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_PirateVest1_line"
		};
		backpack="";
	};
	class XI_Line_Autogun_2_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Line Autogun 2 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_2";
		weapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_autogun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag",
			"ic_30rnd_825_rifleMag"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_beret_light",
			"xi_PirateVest2_line"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_beret_light",
			"xi_PirateVest2_line"
		};
		backpack="";
	};
	class XI_Line_AT_1_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Line AT 1 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"XI_IC_CAD_Rocketlauncher_base",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"XI_IC_CAD_Rocketlauncher_base",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Krak_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"IC_Frag_rocket_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_PirateVest2_line"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_PirateVest2_line"
		};
		backpack="XI_Line_AT_1_Pirate_pack";
	};
	class XI_Line_Melta_1_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Line Melta 1 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_melta",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_melta",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister",
			"ic_melta_canister"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_PirateVest1_line"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_PirateVest1_line"
		};
		backpack="XI_Line_Melta_1_Pirate_pack";
	};
	class XI_Line_Marksman_1_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Line Marksman 1 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_LuciusLongLas_optic_LRPS",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_LuciusLongLas_optic_LRPS",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack",
			"IC_LuciusLongLas_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_ElysianArmour_Line"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_MoebianFlakHelmet_line",
			"xi_ElysianArmour_Line"
		};
		backpack="";
	};
	class XI_Shock_Lasgun_1_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Shock Lasgun 1 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_IC_Hellgun_ic_hellgun_optic",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_IC_Hellgun_ic_hellgun_optic",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_hellgun_mag",
			"ic_hellgun_mag",
			"ic_hellgun_mag"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_hellgun_mag",
			"ic_hellgun_mag",
			"ic_hellgun_mag"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_FeudalHelmetFULL_SHOCK",
			"xi_stormTrooper_v2_Shock"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_FeudalHelmetFULL_SHOCK",
			"xi_stormTrooper_v2_Shock"
		};
		backpack="";
	};
	class XI_Shock_Bolter_1_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Shock Bolter 1 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_bolter",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_bolter",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag",
			"ic_bolt_small_mag"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_FeudalHelmetFULL_SHOCK",
			"xi_stormTrooper_v2_Shock"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_FeudalHelmetFULL_SHOCK",
			"xi_stormTrooper_v2_Shock"
		};
		backpack="";
	};
	class XI_Shock_Xeno_1_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Shock Xeno 1 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_PulseRifleW",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_PulseRifleW",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag",
			"ic_pulseRifle_mag"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_FeudalHelmetFULL_SHOCK",
			"xi_stormTrooper_v2_Shock"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"xi_FeudalHelmetFULL_SHOCK",
			"xi_stormTrooper_v2_Shock"
		};
		backpack="";
	};
	class XI_Light_Crewman_1_Pirate: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Crewman 1 Pirate";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"H_Tank_black_F",
			"xi_PirateVest1_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"H_Tank_black_F",
			"xi_PirateVest1_light"
		};
		backpack="";
	};
	class XI_Light_Crewman_1_Pirate_1: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Crewman 1 Pirate 1";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"H_Tank_black_F",
			"xi_PirateVest1_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"H_Tank_black_F",
			"xi_PirateVest1_light"
		};
		backpack="";
	};
	class XI_Light_Crewman_1_Pirate_2: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Crewman 1 Pirate 2";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"H_Tank_black_F",
			"xi_PirateVest1_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"H_Tank_black_F",
			"xi_PirateVest1_light"
		};
		backpack="";
	};
	class XI_Light_Crewman_1_Pirate_3: B_Soldier_A_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Light Crewman 1 Pirate 3";
		uniformClass="xi_CF_uniform_w_Pirate_1";
		weapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"XI_ic_cad_m36_lasgun",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage"
		};
		magazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		respawnMagazines[]=
		{
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"IC_CAD_SMOKE_mag",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack",
			"ic_las_powerpack"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"H_Tank_black_F",
			"xi_PirateVest1_light"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ACE_Altimeter",
			"H_Tank_black_F",
			"xi_PirateVest1_light"
		};
		backpack="";
	};
	class XI_Pirate_AAA: XI_OPfor_AA_1
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate AAA";
		hiddenSelectionsTextures[]=
		{
			"a3\armor_f_exp\apc_tracked_01\data\apc_tracked_01_aa_body_olive_co.paa",
			"a3\armor_f_exp\apc_tracked_01\data\mbt_01_body_olive_co.paa",
			"a3\armor_f_exp\apc_tracked_01\data\apc_tracked_01_aa_tower_olive_co.paa",
			"a3\armor_f\data\camonet_nato_green_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_1";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_1"
		};
	};
	class XI_Pirate_Multilas: CadianMultilasCarriageTwin
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Multilas";
		hiddenSelectionsTextures[]=
		{
			"cadianhwtweapon\data\autocannon\main\autocannon_co.paa",
			""
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_Autogun: CadianAutocannonCarriageTwin
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Autogun";
		hiddenSelectionsTextures[]=
		{
			"cadianhwtweapon\data\autocannon\main\autocannon_co.paa",
			""
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_HE: XI_TOH_DeathHammer_FixedHE
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate HE";
		hiddenSelectionsTextures[]=
		{
			"cadianhwtweapon\data\autocannon\main\autocannon_co.paa",
			""
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_AT: XI_TOH_DeathHammer_FixedAT
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate AT";
		hiddenSelectionsTextures[]=
		{
			"cadianhwtweapon\data\autocannon\main\autocannon_co.paa",
			""
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_APC: C_mako1_alWood_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate APC";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\mako\data\bodywood_m35_co.paa",
			"meop_vehicles\mako\data\gunwood_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_APC_2: C_makoAA_alWood_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate APC 2";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\mako\data\bodywood_m35_co.paa",
			"meop_vehicles\mako\data\gunwood_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_APC_3: I_M080apc1_merc_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate APC 3";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\apc\data\m080_body_old_co.paa",
			"meop_vehicles\apc\data\m080_cargo_old_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_Supply_Vehicle: C_M080apc2_service_al_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Supply Vehicle";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\apc\data\body_al_co.paa",
			"meop_vehicles\apc\data\cargo_al_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_Transport_car: MEOP_B_veh_LandVan_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Transport car";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\van\data\hull_black.paa",
			"meop_vehicles\van\data\eng_black.paa"
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_Technical: MEOP_B_veh_LandPickupA_gang_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Technical";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\van\data\hullpu_green_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_Dropship_1: MEOP_veh_kodiak3_allianceWood
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Dropship 1";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\kodiak\data\kod_back_green_co.paa",
			"meop_vehicles\kodiak\data\kod_front_green_co.paa",
			"meop_vehicles\kodiak\data\kod_det_green_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_2";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_2"
		};
	};
	class XI_Pirate_Interceptor_1: MEOP_SX3fighter_veh_mercBlue_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Interceptor 1";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\sx3\al\data\cerfighter_clear_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_3";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_3"
		};
	};
	class XI_Pirate_Dropship_Helicopter_1: MEOP_veh_ta62_facinus
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Dropship Helicopter 1";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\a61\data\hullfac_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_2";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_2"
		};
	};
	class XI_Pirate_Dropship_2: MEOP_veh_turKod_BS
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Dropship 2";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\turkodiak\data\hullclear_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_2";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_2"
		};
	};
	class XI_Pirate_Interceptor_2: MEOP_SX4fighter_veh_cerbRed_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Interceptor 2";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\sx3\al\data\cerfighter_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_3";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_3"
		};
	};
	class XI_Pirate_Dropship_Helicopter_2: MEOP_veh_a61_batar
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Dropship Helicopter 2";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\a61\data\a61_batar.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_2";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_2"
		};
	};
	class XI_Pirate_Adavnced_APC: C_hammer1_cerbRed_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Adavnced APC";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\mako\hammer\data\hammer_cerb_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_Light_transport: C_mako_m32_ERCS_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Light transport";
		hiddenSelectionsTextures[]=
		{
			"meop_vehicles\mako\data\bodyercs_m32_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_Light_Tank_1: O_MBT_04_command_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Light Tank 1";
		hiddenSelectionsTextures[]=
		{
			"a3\armor_f_tank\mbt_04\data\mbt_04_exterior_1_co.paa",
			"a3\armor_f_tank\mbt_04\data\mbt_04_exterior_2_co.paa",
			"a3\armor_f\data\camonet_csat_stripe_desert_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_1";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_1"
		};
	};
	class XI_Pirate_Hijacked_Tank_1: O_T_MBT_02_cannon_ghex_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Hijacked Tank 1";
		hiddenSelectionsTextures[]=
		{
			"a3\armor_f_exp\mbt_02\data\mbt_02_body_ghex_co.paa",
			"a3\armor_f_exp\mbt_02\data\mbt_02_turret_ghex_co.paa",
			"a3\armor_f_exp\mbt_02\data\mbt_02_ghex_co.paa",
			"a3\armor_f\data\camonet_csat_hex_green_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_1";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_1"
		};
	};
	class XI_Pirate_Heavy_Tank_Plasma: TIOW_Krieg_LR_Executioner_1489th_OP
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Heavy Tank Plasma";
		hiddenSelectionsTextures[]=
		{
			"apcs\data\textures\chimerainsignia1489th_ca.paa",
			"whtracked\lrmiv\data\lr_krieg1489th_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_1";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_1"
		};
	};
	class XI_Pirate_Heavy_Tank_Battle: TIOW_Krieg_LR_Battlecannon_1489th_OP
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Heavy Tank Battle";
		hiddenSelectionsTextures[]=
		{
			"apcs\data\textures\chimerainsignia1489th_ca.paa",
			"whtracked\lrmiv\data\lr_krieg1489th_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_1";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_1"
		};
	};
	class XI_Pirate_Hijacked_APC: O_T_APC_Wheeled_02_rcws_v2_ghex_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Hijacked APC";
		hiddenSelectionsTextures[]=
		{
			"a3\armor_f_exp\apc_wheeled_02\data\apc_wheeled_02_ext_01_ghex_co.paa",
			"a3\armor_f_exp\apc_wheeled_02\data\apc_wheeled_02_ext_02_ghex_co.paa",
			"a3\data_f_exp\vehicles\turret_ghex_co.paa",
			"a3\armor_f\data\camonet_csat_hex_green_co.paa",
			"a3\armor_f\data\cage_csat_green_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_APC_1: IC_Chimera_01_desert
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate APC 1";
		hiddenSelectionsTextures[]=
		{
			"ic_chimera\data\chimera_hull_helris_co.paa",
			"ic_chimera\data\chimera_tracks_helris_co.paa",
			"ic_chimera\data\chimera_turret_helris_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_1";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_1"
		};
	};
	class XI_Pirate_Destroyer_1: B_T_AFV_Wheeled_01_up_cannon_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Destroyer 1";
		hiddenSelectionsTextures[]=
		{
			"a3\armor_f_tank\afv_wheeled_01\data\afv_wheeled_01_ext1_green_co.paa",
			"a3\armor_f_tank\afv_wheeled_01\data\afv_wheeled_01_ext2_green_co.paa",
			"a3\armor_f_tank\afv_wheeled_01\data\afv_wheeled_01_wheel_green_co.paa",
			"a3\armor_f_tank\afv_wheeled_01\data\afv_wheeled_01_ext3_co.paa",
			"a3\armor_f_tank\afv_wheeled_01\data\afv_commander_tow_co.paa",
			"a3\armor_f\data\camonet_nato_green_co.paa",
			"a3\armor_f_tank\afv_wheeled_01\data\afv_wheeled_01_ext3_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate"
		};
	};
	class XI_Pirate_ARV_1: B_T_APC_Tracked_01_CRV_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate ARV 1";
		hiddenSelectionsTextures[]=
		{
			"a3\armor_f_exp\apc_tracked_01\data\apc_tracked_01_body_crv_olive_co.paa",
			"a3\armor_f_exp\apc_tracked_01\data\mbt_01_body_olive_co.paa",
			"a3\data_f_exp\vehicles\turret_olive_co.paa",
			"a3\armor_f_exp\apc_tracked_01\data\apc_tracked_01_crv_olive_co.paa",
			"a3\armor_f\data\camonet_nato_green_co.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_1";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_1"
		};
	};
	class XI_Pirate_Valkyrie_1: TIOW_Valkyrie_Rocket_AC_B
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Valkyrie 1";
		hiddenSelectionsTextures[]=
		{
			"whair\val\data\valkyrie_dkok_1490th_ca.paa",
			"whair\val\data\valkyrie_dkok_1490th_low_res_ca.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_3";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_3"
		};
	};
	class XI_Pirate_Light_Helicopter_1: B_Heli_Light_01_dynamicLoadout_F
	{
		faction="XI_Sector_Pirates";
		side=0;
		displayName="Pirate Light Helicopter 1";
		hiddenSelectionsTextures[]=
		{
			"a3\air_f\heli_light_01\data\heli_light_01_ext_blufor_co.paa",
			"a3\air_f\heli_light_01\data\heli_light_01_dot_ca.paa"
		};
		crew="XI_Light_Crewman_1_Pirate_2";
		typicalCargo[]=
		{
			"XI_Light_Crewman_1_Pirate_2"
		};
	};
	class XI_Light_AT_1_Pirate_pack: ic_CarryAll
	{
		scope=1;
		class TransportMagazines
		{
			class _xx_IC_Krak_rocket_mag
			{
				count=5;
				magazine="IC_Krak_rocket_mag";
			};
			class _xx_IC_Frag_rocket_mag
			{
				count=4;
				magazine="IC_Frag_rocket_mag";
			};
			class _xx_ic_las_powerpack
			{
				count=4;
				magazine="ic_las_powerpack";
			};
		};
		class TransportItems
		{
		};
		class TransportWeapons
		{
		};
	};
	class XI_Light_Melta_1_Pirate_pack: ic_CarryAll
	{
		scope=1;
		class TransportMagazines
		{
			class _xx_ic_melta_canister
			{
				count=10;
				magazine="ic_melta_canister";
			};
		};
		class TransportItems
		{
		};
		class TransportWeapons
		{
		};
	};
	class XI_Light_Melta_1_Irregular_pack: ic_CarryAll
	{
		scope=1;
		class TransportMagazines
		{
			class _xx_ic_melta_canister
			{
				count=10;
				magazine="ic_melta_canister";
			};
		};
		class TransportItems
		{
		};
		class TransportWeapons
		{
		};
	};
	class XI_Light_AT_1_Irregular_pack: ic_CarryAll
	{
		scope=1;
		class TransportMagazines
		{
			class _xx_IC_Krak_rocket_mag
			{
				count=5;
				magazine="IC_Krak_rocket_mag";
			};
			class _xx_IC_Frag_rocket_mag
			{
				count=4;
				magazine="IC_Frag_rocket_mag";
			};
			class _xx_ic_las_powerpack
			{
				count=4;
				magazine="ic_las_powerpack";
			};
		};
		class TransportItems
		{
		};
		class TransportWeapons
		{
		};
	};
	class XI_Light_AT_1_Skirmisher_pack: ic_CarryAll
	{
		scope=1;
		class TransportMagazines
		{
			class _xx_IC_Krak_rocket_mag
			{
				count=5;
				magazine="IC_Krak_rocket_mag";
			};
			class _xx_IC_Frag_rocket_mag
			{
				count=4;
				magazine="IC_Frag_rocket_mag";
			};
			class _xx_ic_las_powerpack
			{
				count=4;
				magazine="ic_las_powerpack";
			};
		};
		class TransportItems
		{
		};
		class TransportWeapons
		{
		};
	};
	class XI_Light_Melta_1_Skirmisher_pack: ic_CarryAll
	{
		scope=1;
		class TransportMagazines
		{
			class _xx_ic_melta_canister
			{
				count=10;
				magazine="ic_melta_canister";
			};
		};
		class TransportItems
		{
		};
		class TransportWeapons
		{
		};
	};
	class XI_Line_AT_1_Pirate_pack: ic_CarryAll
	{
		scope=1;
		class TransportMagazines
		{
			class _xx_IC_Krak_rocket_mag
			{
				count=5;
				magazine="IC_Krak_rocket_mag";
			};
			class _xx_IC_Frag_rocket_mag
			{
				count=4;
				magazine="IC_Frag_rocket_mag";
			};
			class _xx_ic_las_powerpack
			{
				count=4;
				magazine="ic_las_powerpack";
			};
		};
		class TransportItems
		{
		};
		class TransportWeapons
		{
		};
	};
	class XI_Line_Melta_1_Pirate_pack: ic_CarryAll
	{
		scope=1;
		class TransportMagazines
		{
			class _xx_ic_melta_canister
			{
				count=10;
				magazine="ic_melta_canister";
			};
		};
		class TransportItems
		{
		};
		class TransportWeapons
		{
		};
	};
};
